version: "3.8"
services:
  cookiecutter-service:
    build: .
    image: happymoney/cookiecutter-service
    container_name: cookiecutter-service
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: local
      AMAZON_DYNAMODB_ENDPOINT: http://dynamodb-local:4598/
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka-local:9092
      SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL: http://schema-local:9091
      SWAGGER_BASE_URL: localhost:8080

networks:
  default:
    external: true
    name: happymoney
